//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.Contracts.ViewModels
{
    public partial class ContactInfoModel : BaseModel
    {
        public long ContactInfoID { get; set; }
        public string ContactInfo1 { get; set; }
        public string ContactPerson { get; set; }
        public long ContactTypeID { get; set; }
    }
}
