//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.Contracts.ViewModels
{
    public partial class SearchTermModel : BaseModel
    {
        public long Id { get; set; }
        public string Keyword { get; set; }
        public long StoreId { get; set; }
        public int Count { get; set; }
    }
}
