//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace OMSCloud.Contracts.ViewModels
{
    public partial class OrderStatusMapModel : BaseModel
    {
        public long OrderStatusMapID { get; set; }

        [Required(ErrorMessage = "Parent Order Status Id must be provided, can not leave empty.")]
        [Display(Name = "Parent Order Status Id")]
        public long ParentOrderStatusID { get; set; }

        [Required(ErrorMessage = "Child Order Status Id must be provided, can not leave empty.")]
        [Display(Name = "Child Order Status Id")]
        public long ChildOrderStatusID { get; set; }

        [Required(ErrorMessage = "Status Id must be provided, can not leave empty.")]
        [Display(Name = "Status Id")]
        public long StatusID { get; set; }

        [Required(ErrorMessage = "Parent-Order-Status must be provided, can not leave empty.")]
        [Display(Name = "Parent-Order-Status")]
        public string ParentOrderStatusTitle { get; set; }

        [Required(ErrorMessage = "Next-Order-Status must be provided, can not leave empty.")]
        [Display(Name = "Next Order Status")]
        public string ChildOrderStatusTitle { get; set; }

        [Required(ErrorMessage = "Status must be provided, can not leave empty.")]
        [Display(Name = "Status")]
        public string StatusTitle { get; set; }
         
        [Required(ErrorMessage = "Value for IsDefault must be provided, can not leave empty.")]
        [Display(Name = "Is Default")]
        public bool IsDefault { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}
