//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OMSCloud.Contracts.Common;
using OMSCloud.Contracts.Common.DBEnums;

namespace OMSCloud.Contracts.ViewModels
{
    public partial class PaymentModel : ConcurrencyBaseModel
    {
        public long PaymentID { get; set; }
        public long OrderID { get; set; }
        public string OrderNumber { get; set; }
        public long PayTypeID { get; set; }
        public bool IsPrepaid { get; set; }
        public double Amount { get; set; }
        public string PaymentGatewayTransactionID { get; set; }
        public string PaymentToken { get; set; }
        public bool IsAmountVerified { get; set; }
        public double ActualPayin { get; set; }
        public double ActualPayout { get; set; }
        public double CalculatedPayin { get; set; }
        public double CalculatedPayout { get; set; }
        public long? ShopProvinceID { get; set; } = null;
        public long? ShopCityID { get; set; } = null;
    }

    public class PaymentRequestModel : BaseModel
    {
        public long OrderID { get; set; }
        public DBPaymentMethodEnum PaymentMethod { get; set; }
        public DBDeliveryOptionEnum DeliveryOption { get; set; }
        public long DeliveryAddressID { get; set; }
        public long SelectedProvinceID { get; set; }
        public long SelectedCityID { get; set; }
        public double DeliveryCharges { get; set; }
        public double PaymentAmount { get; set; }
        public double MinOrderLimit { get; set; }
        public long ShopID { get; set; }    
        public string paymentId { get; set; }
        public string token { get; set; }
        public string PayerID { get; set; }
    }
    public class PaymentResponseModel : BaseModel
    {
        public StatusMessage StatusCode { get; set; }
        public string StatusMessage { get; set; }
        public string SessionID { get; set; }
        public string APIKey { get; set; }
        public bool IsRedirectionRequired { get; set; }
    }

    public class SMSRequestModel : BaseModel
    {
        public string SMSText { get; set; }
        public string MobileNumber { get; set; }
    }
    public class SMSResponseModel : BaseModel
    {
        public StatusMessage StatusCode { get; set; }
        public string StatusMessage { get; set; }   
        public string SMSID { get; set; }
    }
}
