--USE [master]
--GO
--/****** Object:  Database [OMS_Security_v0.2]    Script Date: 2/15/2021 11:52:55 AM ******/
--CREATE DATABASE [OMS_Security_v0.2]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'OMSSecurity', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQL2019\MSSQL\DATA\OMSSecurity.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
-- LOG ON 
--( NAME = N'OMSSecurity_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQL2019\MSSQL\DATA\OMSSecurity_log.LDF' , SIZE = 1088KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET COMPATIBILITY_LEVEL = 100
--GO
--IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
--begin
--EXEC [OMS_Security_v0.2].[dbo].[sp_fulltext_database] @action = 'enable'
--end
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET ANSI_NULL_DEFAULT OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET ANSI_NULLS OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET ANSI_PADDING OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET ANSI_WARNINGS OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET ARITHABORT OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET AUTO_CLOSE OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET AUTO_SHRINK OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET AUTO_UPDATE_STATISTICS ON 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET CURSOR_CLOSE_ON_COMMIT OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET CURSOR_DEFAULT  GLOBAL 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET CONCAT_NULL_YIELDS_NULL OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET NUMERIC_ROUNDABORT OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET QUOTED_IDENTIFIER OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET RECURSIVE_TRIGGERS OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET  ENABLE_BROKER 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET DATE_CORRELATION_OPTIMIZATION OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET TRUSTWORTHY OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET PARAMETERIZATION SIMPLE 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET READ_COMMITTED_SNAPSHOT ON 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET HONOR_BROKER_PRIORITY OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET RECOVERY FULL 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET  MULTI_USER 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET PAGE_VERIFY CHECKSUM  
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET DB_CHAINING OFF 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET DELAYED_DURABILITY = DISABLED 
--GO
--EXEC sys.sp_db_vardecimal_storage_format N'OMS_Security_v0.2', N'ON'
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET QUERY_STORE = OFF
--GO
--USE [OMS_Security_v0.2]
--GO
/****** Object:  Table [dbo].[__MigrationHistory]    Script Date: 2/15/2021 11:52:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__MigrationHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ContextKey] [nvarchar](300) NOT NULL,
	[Model] [varbinary](max) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC,
	[ContextKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserClaims]    Script Date: 2/15/2021 11:52:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.AspNetUserClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserLogins]    Script Date: 2/15/2021 11:52:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserLogins](
	[LoginProvider] [nvarchar](128) NOT NULL,
	[ProviderKey] [nvarchar](128) NOT NULL,
	[UserId] [bigint] NOT NULL,
 CONSTRAINT [PK_dbo.AspNetUserLogins] PRIMARY KEY CLUSTERED 
(
	[LoginProvider] ASC,
	[ProviderKey] ASC,
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LNK_ROLE_PERMISSION]    Script Date: 2/15/2021 11:52:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LNK_ROLE_PERMISSION](
	[RoleId] [bigint] NOT NULL,
	[PermissionId] [bigint] NOT NULL,
 CONSTRAINT [PK_dbo.LNK_ROLE_PERMISSION] PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC,
	[PermissionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LNK_USER_ROLE]    Script Date: 2/15/2021 11:52:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LNK_USER_ROLE](
	[UserId] [bigint] NOT NULL,
	[RoleId] [bigint] NOT NULL,
 CONSTRAINT [PK_dbo.LNK_USER_ROLE] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERMISSIONS]    Script Date: 2/15/2021 11:52:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERMISSIONS](
	[PermissionId] [bigint] IDENTITY(1,1) NOT NULL,
	[PermissionDescription] [nvarchar](1000) NOT NULL,
 CONSTRAINT [PK_dbo.PERMISSIONS] PRIMARY KEY CLUSTERED 
(
	[PermissionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLES]    Script Date: 2/15/2021 11:52:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLES](
	[RoleId] [bigint] IDENTITY(1,1) NOT NULL,
	[LastModified] [datetime] NOT NULL,
	[IsSysAdmin] [bit] NOT NULL,
	[RoleDescription] [nvarchar](max) NULL,
	[Name] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_dbo.ROLES] PRIMARY KEY CLUSTERED 
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 2/15/2021 11:52:55 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[UserId] [bigint] IDENTITY(1,1) NOT NULL,
	[LastModified] [datetime] NOT NULL,
	[Inactive] [bit] NOT NULL,
	[Firstname] [nvarchar](max) NULL,
	[Lastname] [nvarchar](max) NULL,
	[Email] [nvarchar](256) NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[SecurityStamp] [nvarchar](max) NULL,
	[PhoneNumber] [nvarchar](max) NULL,
	[PhoneNumberConfirmed] [bit] NOT NULL,
	[TwoFactorEnabled] [bit] NOT NULL,
	[LockoutEndDateUtc] [datetime] NULL,
	[LockoutEnabled] [bit] NOT NULL,
	[AccessFailedCount] [int] NOT NULL,
	[UserName] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_dbo.USERS] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_UserId]    Script Date: 2/15/2021 11:52:55 AM ******/
CREATE NONCLUSTERED INDEX [IX_UserId] ON [dbo].[AspNetUserClaims]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserId]    Script Date: 2/15/2021 11:52:55 AM ******/
CREATE NONCLUSTERED INDEX [IX_UserId] ON [dbo].[AspNetUserLogins]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_PermissionId]    Script Date: 2/15/2021 11:52:55 AM ******/
CREATE NONCLUSTERED INDEX [IX_PermissionId] ON [dbo].[LNK_ROLE_PERMISSION]
(
	[PermissionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RoleId]    Script Date: 2/15/2021 11:52:55 AM ******/
CREATE NONCLUSTERED INDEX [IX_RoleId] ON [dbo].[LNK_ROLE_PERMISSION]
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RoleId]    Script Date: 2/15/2021 11:52:55 AM ******/
CREATE NONCLUSTERED INDEX [IX_RoleId] ON [dbo].[LNK_USER_ROLE]
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserId]    Script Date: 2/15/2021 11:52:55 AM ******/
CREATE NONCLUSTERED INDEX [IX_UserId] ON [dbo].[LNK_USER_ROLE]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [RoleNameIndex]    Script Date: 2/15/2021 11:52:55 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [RoleNameIndex] ON [dbo].[ROLES]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UserNameIndex]    Script Date: 2/15/2021 11:52:55 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UserNameIndex] ON [dbo].[USERS]
(
	[UserName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AspNetUserClaims]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.USERS_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[USERS] ([UserId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserClaims] CHECK CONSTRAINT [FK_dbo.AspNetUserClaims_dbo.USERS_UserId]
GO
ALTER TABLE [dbo].[AspNetUserLogins]  WITH CHECK ADD  CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.USERS_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[USERS] ([UserId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserLogins] CHECK CONSTRAINT [FK_dbo.AspNetUserLogins_dbo.USERS_UserId]
GO
ALTER TABLE [dbo].[LNK_ROLE_PERMISSION]  WITH CHECK ADD  CONSTRAINT [FK_dbo.LNK_ROLE_PERMISSION_dbo.PERMISSIONS_PermissionId] FOREIGN KEY([PermissionId])
REFERENCES [dbo].[PERMISSIONS] ([PermissionId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LNK_ROLE_PERMISSION] CHECK CONSTRAINT [FK_dbo.LNK_ROLE_PERMISSION_dbo.PERMISSIONS_PermissionId]
GO
ALTER TABLE [dbo].[LNK_ROLE_PERMISSION]  WITH CHECK ADD  CONSTRAINT [FK_dbo.LNK_ROLE_PERMISSION_dbo.ROLES_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[ROLES] ([RoleId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LNK_ROLE_PERMISSION] CHECK CONSTRAINT [FK_dbo.LNK_ROLE_PERMISSION_dbo.ROLES_RoleId]
GO
ALTER TABLE [dbo].[LNK_USER_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_dbo.LNK_USER_ROLE_dbo.ROLES_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[ROLES] ([RoleId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LNK_USER_ROLE] CHECK CONSTRAINT [FK_dbo.LNK_USER_ROLE_dbo.ROLES_RoleId]
GO
ALTER TABLE [dbo].[LNK_USER_ROLE]  WITH CHECK ADD  CONSTRAINT [FK_dbo.LNK_USER_ROLE_dbo.USERS_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[USERS] ([UserId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LNK_USER_ROLE] CHECK CONSTRAINT [FK_dbo.LNK_USER_ROLE_dbo.USERS_UserId]
GO
--USE [master]
--GO
--ALTER DATABASE [OMS_Security_v0.2] SET  READ_WRITE 
--GO
