//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressContactInfoPair
    {
        public long AddressContactInfoPairID { get; set; }
        public long AddressID { get; set; }
        public long ContactInfoID { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual Address Address { get; set; }
    }
}
