//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.AddressContactInfoPair = new HashSet<AddressContactInfoPair>();
            this.OrderDeliveryDetail = new HashSet<OrderDeliveryDetail>();
        }
    
        public long AddressID { get; set; }
        public long ProfileID { get; set; }
        public int AddressTypeID { get; set; }
        public string PlotNumber { get; set; }
        public string StreetNumber { get; set; }
        public long LocationID { get; set; }
        public string NearestLandmark { get; set; }
        public string PostalCode { get; set; }
        public string MapLink { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public long CreatedByUserID { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public long LastModifiedByUserID { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> ProvinceID { get; set; }
        public Nullable<long> CityID { get; set; }
    
        public virtual Profile Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressContactInfoPair> AddressContactInfoPair { get; set; }
        public virtual AddressType AddressType { get; set; }
        public virtual LocationTree LocationTree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDeliveryDetail> OrderDeliveryDetail { get; set; }
    }
}
