//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attribute()
        {
            this.CategoryAttributePair = new HashSet<CategoryAttributePair>();
            this.ProductAttributePair = new HashSet<ProductAttributePair>();
            this.CartItemAttributePair = new HashSet<CartItemAttributePair>();
        }
    
        public long AttributeID { get; set; }
        public string AttributeTitle { get; set; }
        public string Description { get; set; }
        public long AttributeTypeID { get; set; }
        public long DataTypeID { get; set; }
        public long DataTypeSize { get; set; }
        public string DefaultValue { get; set; }
        public bool IsMandatory { get; set; }
        public long StatusID { get; set; }
        public long CreatedByUserID { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public bool IsSystem { get; set; }
        public bool IsMultiSelect { get; set; }
    
        public virtual AttributeType AttributeType { get; set; }
        public virtual DataType DataType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryAttributePair> CategoryAttributePair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAttributePair> ProductAttributePair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItemAttributePair> CartItemAttributePair { get; set; }
    }
}
