//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public long BankId { get; set; }
        public long SupplierId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string AccountTitle { get; set; }
        public string AccountNumber { get; set; }
        public string IBAN { get; set; }
        public Nullable<int> AccountTypeId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
