//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            this.Product = new HashSet<Product>();
        }
    
        public long BrandID { get; set; }
        public string BrandName { get; set; }
        public string ManufacturerName { get; set; }
        public string Description { get; set; }
        public long StatusID { get; set; }
        public long CreatedByUserID { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public bool IsSystem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
