//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CartOrder()
        {
            this.CartItem = new HashSet<CartItem>();
            this.CartOrder1 = new HashSet<CartOrder>();
            this.OrderPayment = new HashSet<OrderPayment>();
            this.Payment = new HashSet<Payment>();
        }
    
        public long CartOrderID { get; set; }
        public Nullable<long> ParentCartID { get; set; }
        public long BuyerProfileID { get; set; }
        public long OrderStatusID { get; set; }
        public long StatusID { get; set; }
        public Nullable<long> DeliveryAddressID { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<long> OrderSupplierId { get; set; }
        public Nullable<long> SupplierDeliveryOptionPairID { get; set; }
        public double OrderTotal { get; set; }
        public double TaxTotal { get; set; }
        public double DeliveryTotal { get; set; }
        public double DiscountTotal { get; set; }
        public double PaymentTotal { get; set; }
        public double CalculatedPayout { get; set; }
        public double ActualPayout { get; set; }
        public double CalculatedPayIn { get; set; }
        public double ActualPayIn { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public long CreatedByUserID { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public long LastModifiedByUserID { get; set; }
        public string OrderNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartOrder> CartOrder1 { get; set; }
        public virtual CartOrder CartOrder2 { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual SupplierDeliveryOptionPair SupplierDeliveryOptionPair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPayment> OrderPayment { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
