//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CartItem()
        {
            this.CartItemAttributePair = new HashSet<CartItemAttributePair>();
        }
    
        public long CartItemID { get; set; }
        public long CartOrderID { get; set; }
        public long ProductID { get; set; }
        public long Quantity { get; set; }
        public double TaxRateApplied { get; set; }
        public double TaxAmount { get; set; }
        public double DiscountAmount { get; set; }
        public double ItemTotalPrice { get; set; }
        public long StatusID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public long CreatedByUserID { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public long LastModifiedByUserID { get; set; }
        public double UnitPrice { get; set; }
        public Nullable<long> ParentCartItemID { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItemAttributePair> CartItemAttributePair { get; set; }
        public virtual CartOrder CartOrder { get; set; }
    }
}
