//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItemAttributePair
    {
        public long CartItemAttributeId { get; set; }
        public long CartItemID { get; set; }
        public long AttributeID { get; set; }
        public string AttributeValue { get; set; }
        public Nullable<double> VariationInPrice { get; set; }
        public Nullable<long> OrderItemID { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual CartItem CartItem { get; set; }
    }
}
