//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryAttributePair
    {
        public long CategoryAttributePairID { get; set; }
        public long CategoryID { get; set; }
        public long AttributeID { get; set; }
        public string AttributeValue { get; set; }
        public Nullable<long> DisplayOrder { get; set; }
        public bool IsAssigned { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Category Category { get; set; }
    }
}
