//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public long MessageId { get; set; }
        public string MessageCode { get; set; }
        public long ChatId { get; set; }
        public long SenderProfileId { get; set; }
        public long ReceiverProfileId { get; set; }
        public string Message { get; set; }
        public System.DateTime SentDateTime { get; set; }
        public string ReadDateTime { get; set; }
        public bool IsReceived { get; set; }
        public bool IsRead { get; set; }
        public long StatusId { get; set; }
    
        public virtual Chat Chat { get; set; }
    }
}
