//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReview
    {
        public long CustomerReviewID { get; set; }
        public long SubjectRowID { get; set; }
        public long SubjectID { get; set; }
        public string ReviewText { get; set; }
        public short Rating { get; set; }
        public long StatusID { get; set; }
        public long CreatedByUserID { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    }
}
