//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExecAction()
        {
            this.ExecActionParam = new HashSet<ExecActionParam>();
            this.Option = new HashSet<Option>();
        }
    
        public long ExecActionID { get; set; }
        public long DataTypeID { get; set; }
        public string Method { get; set; }
    
        public virtual DataType DataType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecActionParam> ExecActionParam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Option> Option { get; set; }
    }
}
