//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecActionParam
    {
        public long ExecActionParamID { get; set; }
        public long ExecActionID { get; set; }
        public string ParamName { get; set; }
        public long DataTypeID { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual ExecAction ExecAction { get; set; }
    }
}
