//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.GroupRolePair = new HashSet<GroupRolePair>();
        }
    
        public long GroupID { get; set; }
        public string GroupTitle { get; set; }
        public string Description { get; set; }
        public string IconPath { get; set; }
        public long StatusID { get; set; }
        public bool IsSystem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupRolePair> GroupRolePair { get; set; }
    }
}
