//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRolePair
    {
        public long GroupRolePairID { get; set; }
        public long GroupID { get; set; }
        public long RoleID { get; set; }
        public bool IsSystem { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Role Role { get; set; }
    }
}
