//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationToken
    {
        public long TokenId { get; set; }
        public string Token { get; set; }
        public long ProfileId { get; set; }
        public string DevicePlatform { get; set; }
        public string NotificationService { get; set; }
        public long StatusId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string DeviceId { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
