//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notify
    {
        public long NotificationId { get; set; }
        public long NotificationType { get; set; }
        public long SenderProfileId { get; set; }
        public long ReceiverProfileId { get; set; }
        public long StatusId { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public long CreatedByUserID { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public long LastModifiedByUserID { get; set; }
        public long SubjectRowID { get; set; }
    }
}
