//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Option()
        {
            this.Option1 = new HashSet<Option>();
            this.RoleOptionPair = new HashSet<RoleOptionPair>();
        }
    
        public long OptionID { get; set; }
        public string OptionTitle { get; set; }
        public string MenuTitle { get; set; }
        public string ItemTitle { get; set; }
        public string PageURL { get; set; }
        public string NextPageURL { get; set; }
        public int ModuleID { get; set; }
        public int OptionTypeID { get; set; }
        public long ParentOptionID { get; set; }
        public long ExecActionID { get; set; }
        public int StatusID { get; set; }
        public int CreatedByUserID { get; set; }
        public int LastModifiedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ExecAction ExecAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Option> Option1 { get; set; }
        public virtual Option Option2 { get; set; }
        public virtual OptionType OptionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleOptionPair> RoleOptionPair { get; set; }
    }
}
