//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public long OrderPaymentID { get; set; }
        public long CartOrderID { get; set; }
        public long PaymentID { get; set; }
        public double Amount { get; set; }
        public long BillingAddressID { get; set; }
    
        public virtual CartOrder CartOrder { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
