//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusMap
    {
        public long OrderStatusMapID { get; set; }
        public long ParentOrderStatusID { get; set; }
        public long ChildOrderStatusID { get; set; }
        public long StatusID { get; set; }
        public string Description { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual OrderStatus OrderStatus1 { get; set; }
    }
}
