//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDeliveryDetail
    {
        public long OrderDeliveryDetailID { get; set; }
        public long CartOrderID { get; set; }
        public long DeliveryAddressID { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
