//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagedProduct
    {
        public long PackageID { get; set; }
        public long ProductID { get; set; }
        public long ChildProductID { get; set; }
        public long Quantity { get; set; }
        public bool IncludedByDefault { get; set; }
        public Nullable<double> PercentagePrice { get; set; }
        public string OtherDetails { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
