//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.OrderPayment = new HashSet<OrderPayment>();
        }
    
        public long PaymentID { get; set; }
        public long OrderID { get; set; }
        public long PayTypeID { get; set; }
        public double Amount { get; set; }
        public string PaymentGatewayTransactionID { get; set; }
        public string PaymentToken { get; set; }
        public bool IsAmountVerified { get; set; }
        public long CreatedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        public virtual CartOrder CartOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPayment> OrderPayment { get; set; }
        public virtual PayType PayType { get; set; }
    }
}
