//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayOptionMatrix
    {
        public long PayOptionMatrixID { get; set; }
        public long PayModeID { get; set; }
        public long PayTypeID { get; set; }
        public bool IsSystem { get; set; }
    
        public virtual PayMode PayMode { get; set; }
        public virtual PayType PayType { get; set; }
    }
}
