//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMediaDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductMediaDetail()
        {
            this.ProductViewItem = new HashSet<ProductViewItem>();
        }
    
        public long ProductMediaID { get; set; }
        public string ProductMediaTitle { get; set; }
        public string Description { get; set; }
        public long MediaContentTypeID { get; set; }
        public string MediaFilePath { get; set; }
        public long ProductID { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> TransparencyLevel { get; set; }
        public long StatusID { get; set; }
        public long CreatedByUserID { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public Nullable<long> ApprovedByUserID { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
    
        public virtual MediaContentType MediaContentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductViewItem> ProductViewItem { get; set; }
        public virtual Product Product { get; set; }
    }
}
