//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttributePair
    {
        public long ProductAttributePairID { get; set; }
        public long ProductID { get; set; }
        public long AttributeID { get; set; }
        public string AttributeValue { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public bool IsAssigned { get; set; }
        public bool IsSelectedForVariation { get; set; }
        public double VariationInPrice { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Product Product { get; set; }
    }
}
