//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductViewItem
    {
        public long ProductViewProductID { get; set; }
        public long ProductViewID { get; set; }
        public long ProductID { get; set; }
        public long ProductMediaID { get; set; }
    
        public virtual ProductMediaDetail ProductMediaDetail { get; set; }
        public virtual ProductView ProductView { get; set; }
        public virtual Product Product { get; set; }
    }
}
