//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CartItem = new HashSet<CartItem>();
            this.PackagedProduct = new HashSet<PackagedProduct>();
            this.PackagedProduct1 = new HashSet<PackagedProduct>();
            this.ProductAttributePair = new HashSet<ProductAttributePair>();
            this.ProductCategoryPair = new HashSet<ProductCategoryPair>();
            this.ProductMediaDetail = new HashSet<ProductMediaDetail>();
            this.ProductViewItem = new HashSet<ProductViewItem>();
        }
    
        public long ProductID { get; set; }
        public string ProductTitle { get; set; }
        public string BrifeDescription { get; set; }
        public string ProductActualImagePath { get; set; }
        public string ProductImagePath { get; set; }
        public Nullable<long> StockCount { get; set; }
        public string WebLink { get; set; }
        public Nullable<double> BasePrice { get; set; }
        public Nullable<double> DiscountValue { get; set; }
        public Nullable<bool> IsDiscountPercentage { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public long OrderResponseTime { get; set; }
        public string OrderResponseTimeUnitID { get; set; }
        public long TaxTypeID { get; set; }
        public Nullable<int> UserRating { get; set; }
        public Nullable<int> AnalysisRank { get; set; }
        public string Description { get; set; }
        public long ProductTypeID { get; set; }
        public long BrandID { get; set; }
        public long SupplierID { get; set; }
        public long StatusID { get; set; }
        public long CreatedByUserID { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackagedProduct> PackagedProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackagedProduct> PackagedProduct1 { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TaxType TaxType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAttributePair> ProductAttributePair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategoryPair> ProductCategoryPair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMediaDetail> ProductMediaDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductViewItem> ProductViewItem { get; set; }
    }
}
