//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileVerification
    {
        public long VerificationID { get; set; }
        public long DocumentTypeID { get; set; }
        public Nullable<long> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public string Comments { get; set; }
        public Nullable<long> VerificationStatusID { get; set; }
        public long ProfileID { get; set; }
        public string DocumentNumberByUser { get; set; }
        public string DocumentNumberByVerifier { get; set; }
        public string DocumentImagePath { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual VerificationStatus VerificationStatus { get; set; }
    }
}
