//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleOptionPair
    {
        public long RoleOptionPairID { get; set; }
        public long OptionID { get; set; }
        public long RoleID { get; set; }
        public bool IsAssigned { get; set; }
        public bool IsSystem { get; set; }
        public long StatusID { get; set; }
        public long CreatedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Role Role { get; set; }
    }
}
