//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public long ScheduleID { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public Nullable<long> ScheduleTypeID { get; set; }
        public bool IsException { get; set; }
        public string WeekDays { get; set; }
        public Nullable<short> FromDay { get; set; }
        public Nullable<short> ToDay { get; set; }
        public Nullable<short> Month { get; set; }
        public Nullable<short> MonthDay { get; set; }
        public Nullable<long> StatusID { get; set; }
        public string Notes { get; set; }
        public long CreatedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        public virtual ScheduleType ScheduleType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
