//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateMachineState
    {
        public long StateMachineStateID { get; set; }
        public long StateID { get; set; }
        public Nullable<long> NextStateID { get; set; }
        public string NextInputString { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual OrderStatus OrderStatus1 { get; set; }
    }
}
