//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateMachine
    {
        public long StateMachineID { get; set; }
        public long StartStateID { get; set; }
        public string StateMachineTitle { get; set; }
        public string StateMachineDescription { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
