//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.CartOrder = new HashSet<CartOrder>();
            this.Product = new HashSet<Product>();
            this.SupplierDeliveryOptionPair = new HashSet<SupplierDeliveryOptionPair>();
            this.Schedule = new HashSet<Schedule>();
            this.BankAccount = new HashSet<BankAccount>();
        }
    
        public long SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string Logo { get; set; }
        public string Description { get; set; }
        public long StatusID { get; set; }
        public string StatusNotes { get; set; }
        public long BusinessAddressID { get; set; }
        public bool IsBusinessAddressVisible { get; set; }
        public Nullable<long> LanguageID { get; set; }
        public Nullable<long> CurrencyID { get; set; }
        public long CreatedByUserID { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public bool IsCOD { get; set; }
        public long ProfileID { get; set; }
        public double ProcessingFee { get; set; }
        public double PaymentGatewayFee { get; set; }
        public bool IsProcessingFeePercentage { get; set; }
        public bool IsPaymentGatewayFeePercentage { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<long> ProvinceID { get; set; }
        public Nullable<long> CityID { get; set; }
        public string WebLinksJSON { get; set; }
        public string AnnouncementHTML { get; set; }
        public string PolicyHTML { get; set; }
        public string FAQHTML { get; set; }
        public string CategoryRequests { get; set; }
        public string AttributeRequests { get; set; }
        public bool TaxConcent { get; set; }
        public string TaxRegistration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartOrder> CartOrder { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        public virtual Profile Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierDeliveryOptionPair> SupplierDeliveryOptionPair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAccount> BankAccount { get; set; }
    }
}
