//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierDeliveryOptionPair
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierDeliveryOptionPair()
        {
            this.CartOrder = new HashSet<CartOrder>();
        }
    
        public long SupplierDeliveryOptionPairID { get; set; }
        public long SupplierID { get; set; }
        public long DeliveryOptionID { get; set; }
        public double DeliveryCharges { get; set; }
        public double MinOrderLimit { get; set; }
        public string SurroundingCitiesIDs { get; set; }
        public long StatusID { get; set; }
        public long CreatedByUserID { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartOrder> CartOrder { get; set; }
        public virtual DeliveryOption DeliveryOption { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
