//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public long TaxID { get; set; }
        public double TaxValue { get; set; }
        public long TaxTypeID { get; set; }
        public string Description { get; set; }
        public long StatusID { get; set; }
        public bool IsPercentage { get; set; }
        public long LocationLevelId { get; set; }
        public long LocationId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public long CreatedByUserID { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    
        public virtual TaxType TaxType { get; set; }
    }
}
