//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSCloud.DataStore.EF.OMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string Useremail { get; set; }
        public string PasswordResetCode { get; set; }
        public string AcvtivationGUID { get; set; }
        public Nullable<long> UserTypeID { get; set; }
        public long StatusID { get; set; }
        public bool IsLoggedIn { get; set; }
        public bool IsSystem { get; set; }
        public long GroupID { get; set; }
        public long CreatedByUserID { get; set; }
        public long LastModifiedByUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime LastModifiedDateTime { get; set; }
        public Nullable<long> ApprovedByUserID { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
